# Generated by Django 4.0.6 on 2022-07-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taste',
            old_name='product_stastes',
            new_name='products_tastes',
        ),
        migrations.AlterModelTable(
            name='graindbyproduct',
            table='gainding_by_products',
        ),
        migrations.AlterModelTable(
            name='tastebyproduct',
            table='taste_by_products',
        ),
    ]
