# Generated by Django 4.0.6 on 2022-07-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_size_size_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rosting_date',
            new_name='roasting_date',
        ),
    ]
