# Generated by Django 4.0.6 on 2022-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_rosting_date_product_roasting_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='graindbyproduct',
            table='grainding_by_products',
        ),
    ]
